/**
 * Flowtype definitions for consts
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.12.1
 */

declare module "consts" {
  declare export var C0A: 1;
  declare export var C0B: {
    +foo: "bar",
    ...
  };
  declare export { C1A, C1B } from "consts/src/consts1";
}
