/**
 * Flowtype definitions for consts
 * Generated by @keik/generate-flow-types-from-ts-package
 */

declare module "consts" {
  declare export var C0A: 1;
  declare export var C0B: {
    +foo: "bar",
  };
  declare export { C1A, C1B } from "consts/src/consts1";

  declare var C2: {
    A: 1,
    B: {
      +foo: "bar",
    },
  };
  declare export { C2 };
}

declare module "consts/src/consts1" {
  declare export var C1A: 1;
  declare export var C1B: {
    +foo: "bar",
  };
}
