/**
 * Flowtype definitions for fns
 * Generated by @keik/generate-flow-types-from-ts-package
 */

declare module "fns" {
  import type { T0B, T2C } from "types";

  declare var Fns1: {
    f1a: () => number,
    f1b: () => T0B,
    f1c: () => T2C,
  };
  declare export { Fns1 };
}
